# Usa una imagen base de Python
FROM python:3.9-slim

# Selecciona el directorio
WORKDIR /app

#
COPY . /app

# Instala los requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Instala Ansible
RUN apt-get update && \
    apt-get install -y ansible && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Copia los playbooks en el contenedor
COPY playbooks /app/playbooks

# Abre el puerto 5000
EXPOSE 5000

#
ENV FLASK_APP=app.py

#
CMD ["flask", "run", "--host=0.0.0.0"]